<div class="map-enquiry">
  <div class="map-container-wrapper">
  <div class="map-container">
    <img class="map" src="sites/canada.dtdc.com/themes/ca_dtdc/images/map.png" class="img-responsive"/>
        <div class="svg-wrapper">
        <svg id="Layer_1" class="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 324.61 150.83">
           

           <g id="main-0" style="position:absolute; top:-899px;">

              <animate xlink:href="#back" attributeName="r" from="2.3" to="3.5" dur="1s" begin="0s" repeatCount="indefinite" fill="freeze"/>
              <animate xlink:href="#back"
                 attributeType="CSS" attributeName="opacity" from="1" to="0" dur="1s" begin="0s" repeatCount="indefinite" fill="freeze"/>

              <circle id="back" class="back" cx="73" cy="50" r="" stroke-width="0.233"></circle>
              <circle class="front" cx="73" cy="50" r="1.2"/>
             <text text-anchor="middle" fill="#000">USA</text>
           </g>
        </svg>
          <div class="popup pop-wrapper" style="display:none">
             <div class="" id="name"></div>
             <div class="" id="address"></div>
             <div class="clear"></div>
          </div>
          <div class="clear"></div>
        </div><!-- svg wrapper close -->
  <div class="clear"></div>
  </div><!-- container close -->
  </div>
  <div class="enquiry">
    <h4>For Global Business Enquiries please write to: <a href="mailto:gmo@dtdc.com">gmo@dtdc.com</a></h4>
  </div>
</div>
