<?php
global $base_url;

/**
* Implements hook_block_info().
*/
function custom_tabs_block_block_info() {
  $blocks = array();

  $blocks['custom_service_tabs_block'] = array(
    'info' => t('custom service tab block'),
  );
  $blocks['custom_careers_tabs_block'] = array(
    'info' => t('custom careers tab block'),
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function custom_tabs_block_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'custom_service_tabs_block':
        $block['subject'] = '';
        $block['content'] = custom_service_tabs_block_content();
        break;
    case 'custom_careers_tabs_block':
        $block['subject'] = '';
        $block['content'] = custom_careers_tabs_block_content();
        break;

  }

  return $block;
}
// Custom tabs Block

function custom_service_tabs_block_content(){
  $output = array();
  $output = "";
  $result = db_select('node','n')
      ->fields('n')
      ->condition('status',1,'=')
      ->condition('type','product_services','=')
      ->orderBy('created', 'DESC')
      ->execute();
      foreach ($result as $term) {
      $uri = $_SERVER['REQUEST_URI'];
  		$array = explode('/',$uri);
      $nid = $term->nid;
      $node_details = node_load($nid);
      //print_r($node_details);
      $title = $node_details->title;
      $content = $node_details->body['und'][0]['value'];
      $sub_title_id = $node_details->field_service_id['und'][0]['value'];
      $id = strtolower(str_replace(' ', '', ($sub_title_id)));
      $img_id = $node_details->field_product_image['und'][0]['fid'];
      $file = file_load($img_id);
      $uri = $file->uri;
      $url = file_create_url($uri);
      if($array['1'] == 'product-services' && $id == 'international'){
     $output .='<div role="tabpanel" class="tab-pane active" id="'.$id.'">';
      }
      else{
       $output .='<div role="tabpanel" class="tab-pane" id="'.$id.'">';
      }

     $output .='<div class="media"><div class="media-left"><img class="media-object img-responsive" src="'.$url.'" /><div class="clear"></div></div><div class="media-body"><h3 class="media-heading">'.$title.'</h3><div class="dt-line1"></div>'.$content.'<div class="clear"></div></div><div class="clear"></div></div><div class="clear"></div></div>';
     }

  return $output;

}


function custom_careers_tabs_block_content(){
  $output = array();
  $output = "";
  $result = db_select('node','n')
      ->fields('n')
      ->condition('status',1,'=')
      ->condition('type','careers','=')
      ->orderBy('created', 'DESC')
      ->execute();

      foreach ($result as $term) {
      $uri = $_SERVER['REQUEST_URI'];
  		$array = explode('/',$uri);
      $nid = $term->nid;
      $node_details = node_load($nid);
      $title = $node_details->title;
      $id = strtolower(str_replace(' ', '', ($title)));
      $content = $node_details->body['und'][0]['value'];
      $img_id = $node_details->field_image['und'][0]['fid'];
      $file = file_load($img_id);
      $uri = $file->uri;
      $url = file_create_url($uri);
      if($array['1'] == 'careers' && $id == 'opportunities'){
     $output .='<div role="tabpanel" class="tab-pane active" id="'.$id.'">';
      }
      else{
       $output .='<div role="tabpanel" class="tab-pane" id="'.$id.'">';
      }

     $output .='<div class="media"><div class="media-left"><img class="media-object img-responsive" src="'.$url.'" /><div class="clear"></div></div><div class="media-body"><h3 class="media-heading">'.$title.'</h3><div class="dt-line1"></div>'.$content.'<div class="clear"></div></div><div class="clear"></div></div><div class="clear"></div></div>';
     }

  return $output;

}

function custom_tabs_block_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id = 'search-block-form') {
   $form['#attributes']['class'][] = 'navbar-form navbar-left';
  }
}
?>
