<div class="map-enquiry">
  <div class="map-container-wrapper">
  <div class="map-container">
    <img class="map" src="sites/canada.dtdc.com/themes/ca_dtdc/images/map.png" class="img-responsive"/>
        <div class="svg-wrapper">
        <svg id="Layer_1" class="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 324.61 150.83">
           <!-- <polygon class="cls-1" points="236.2 47.98 224.32 18.96 250.02 4.23 236.2 47.98"/>
           <polyline class="cls-1" points="284.07 100.97 251.82 76.78 236.2 47.98 209.12 64.41 199.77 17.25 149.31 16.26"/>
           <polygon class="cls-1" points="162.44 117.83 168.48 89.06 145.89 77.69 162.44 117.83"/>
           <path class="cls-1" d="M269.27,141" transform="translate(-52.58 -41.99)"/>
           <polygon class="cls-1" points="283.62 100.97 320.57 147.01 285.03 136.18 283.62 100.97"/>
           <polyline class="cls-1" points="267.62 33.12 256.86 38.21 236.2 47.98 152.58 39.6 168.48 89.06 171.9 57.43 209.12 64.41 168.48 89.06 191.04 114.23 145.89 77.69 171.9 57.43 236.2 47.98 199.77 17.25"/>
           <line class="cls-1" x1="209.12" y1="64.41" x2="173.69" y2="31.32"/>
           <polygon class="cls-1" points="0.09 28.99 28.25 43.97 30.6 12.35 2.39 0.12 0.09 28.99"/>
           <polyline class="cls-1" points="2.39 0.12 28.25 43.97 95.29 3.73 149.31 16.26 113.39 79.28 145.89 77.69 152.58 39.6 149.31 16.26 173.69 31.32 236.2 47.98 284.07 101.47"/>
           <polygon class="cls-1" points="35.72 102.38 4.83 67.45 28.25 43.97 35.72 102.38"/>
           <path class="cls-1" d="M147.87,173.56" transform="translate(-52.58 -41.99)"/>
           <polyline class="cls-1" points="162.44 117.83 154.33 134.59 145.89 77.69 236.2 47.98 28.25 43.97 113.39 79.28"/>
           <line class="cls-1" x1="227.82" y1="73.36" x2="236.2" y2="47.98"/>
           <polyline class="cls-1" points="152.58 39.6 28.25 43.97 154.33 134.59 285.03 136.18"/>
           <path class="cls-1" d="M147.87,45.71" transform="translate(-52.58 -41.99)"/>
           <polyline class="cls-1" points="95.29 3.73 30.6 12.35 6.83 47.86 28.25 43.97 39.37 73.51 66.29 117.83 35.72 102.38 42.39 149.25 66.29 117.83"/>
           <polyline class="cls-1" points="4.83 67.45 39.37 73.51 35.72 102.38"/> -->

           <g id="main-0" style="position:absolute; top:-899px;">

              <animate xlink:href="#back" attributeName="r" from="2.3" to="3.5" dur="1s" begin="0s" repeatCount="indefinite" fill="freeze"/>
              <animate xlink:href="#back"
                 attributeType="CSS" attributeName="opacity" from="1" to="0" dur="1s" begin="0s" repeatCount="indefinite" fill="freeze"/>

              <circle id="back" class="back" cx="73" cy="50" r="" stroke-width="0.233"></circle>
              <circle class="front" cx="73" cy="50" r="1.2"/>
             <text text-anchor="middle" fill="#000">USA</text>
           </g>
        </svg>
          <div class="popup pop-wrapper" style="display:none">
             <div class="" id="name"></div>
             <div class="" id="address"></div>
             <div class="clear"></div>
          </div>
          <div class="clear"></div>
        </div><!-- svg wrapper close -->
  <div class="clear"></div>
  </div><!-- container close -->
  </div>
  <div class="enquiry">
    <h4>For Global Business Enquiries please write to: <a href="mailto:gmo@dtdc.com">gmo@dtdc.com</a></h4>
  </div>
</div>
